# Generated by Django 5.1.3 on 2024-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default='placeholder', max_length=1000),
            preserve_default=False,
        ),
    ]
