# Generated by Django 5.1.3 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.URLField(default='placeholders'),
            preserve_default=False,
        ),
    ]
