# Generated by Django 5.1.1 on 2025-04-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
