# Generated by Django 5.1.1 on 2025-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('electrical', 'Electrical'), ('luxury', 'Luxury')], default='classic', max_length=20),
        ),
    ]
