# Generated by Django 5.1.1 on 2025-04-11 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_images_product_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="A list of key features (e.g., 'Turbo engine', 'Leather seats')", size=None),
        ),
    ]
