# Generated by Django 5.1.1 on 2025-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_key_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acceleration_0_100',
            field=models.CharField(blank=True, help_text="0-100 km/h acceleration time (e.g., '4.3 seconds')", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text="Dimensions L×W×H (e.g., '5,289 mm × 1,954 mm × 1,503 mm')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(blank=True, help_text="Engine configuration (e.g., '4.0L Twin-Turbo V8')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_economy',
            field=models.CharField(blank=True, help_text="Fuel consumption (e.g., '10.2 L/100km (combined)')", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_tank_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Fuel tank capacity in liters', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, help_text="Power output (e.g., '496 hp @ 5,500 rpm')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='top_speed',
            field=models.CharField(blank=True, help_text="Top speed (e.g., '250 km/h (electronically limited)')", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='torque',
            field=models.CharField(blank=True, help_text="Torque output (e.g., '700 Nm @ 2,000-4,500 rpm')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, help_text="Transmission type (e.g., '9G-TRONIC 9-Speed Automatic')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='trunk_capacity_liters',
            field=models.PositiveIntegerField(blank=True, help_text='Trunk capacity in liters', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Curb weight in kilograms', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wheelbase_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Wheelbase in millimeters', null=True),
        ),
    ]
