# Generated by Django 5.1.1 on 2025-04-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_picture_url',
        ),
    ]
